services:
  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  app:
    image: vav87/devopsforprogrammersproject
    command: npm test
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
volumes:
  pgdata: